services:
    ImageRepositoryBundle\Service\ImageUploader:
        class: ImageRepositoryBundle\Service\ImageUploader
        arguments:
            $uploader: '@Wolnosciowiec\FileRepositoryBundle\Service\FileUploader'
            $imageTags: ['%file_repository_tag%']

    ImageRepositoryBundle\Service\ImageExtractor:
        class: ImageRepositoryBundle\Service\ImageExtractor

    ImageRepositoryBundle\Processor\FeedProcessor:
        class: ImageRepositoryBundle\Service\Processor\FeedProcessor
        arguments:
            $uploader: '@ImageRepositoryBundle\Service\ImageUploader'
            $extractor: '@ImageRepositoryBundle\Service\ImageExtractor'
            $logger: "@logger"
            $enabled: '%file_repository_enabled%'
        tags:
            - kernel.event_subscriber

    ImageRepositoryBundle\Processor\FeedSourceProcessor:
        class: ImageRepositoryBundle\Service\Processor\FeedSourceProcessor
        arguments:
            $uploader: '@ImageRepositoryBundle\Service\ImageUploader'
            $extractor: '@ImageRepositoryBundle\Service\ImageExtractor'
            $logger: "@logger"
            $enabled: '%file_repository_enabled%'
        tags:
            - kernel.event_subscriber
