api.newsboard:
    prefix: /api/news_board
    resource: news_board.yml

api.feed_source:
    prefix: /api/feed_source
    resource: feed_source.yml

api.feed:
    prefix: /api/feed
    resource: feed.yml
