imports:
    - { resource: parameters.php }
    - { resource: security.yml }
    - { resource: services.yml }

parameters:
    locale: en

framework:
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    validation: { enable_annotations: true }
    default_locale: '%locale%'
    trusted_hosts: ~
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Doctrine Configuration
doctrine:
    dbal:
        driver: '%database_driver%'
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci
        path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

        mappings:
            FileRepositoryBundle:
                type: yml
                prefix: Wolnosciowiec\FileRepositoryBundle
                dir: Resources/config/doctrine
                alias: FileRepositoryBundle

doctrine_migrations:
    dir_name: "%kernel.root_dir%/DoctrineMigrations"
    namespace: Application\Migrations
    table_name: migration_versions
    name: Application Migrations
    organize_migrations: false

file_repository:
    cache_class: "Doctrine\\Common\\Cache\\%file_repository_cache_name%Cache"
    url: "%file_repository_url%"
    token: "%file_repository_token%"

liip_monitor:
    enable_controller: true
    checks:
        doctrine_dbal: default
        security_advisory:
            lock_file: '%kernel.root_dir%/../composer.lock'
        readable_directory: ["%kernel.cache_dir%"]
        writable_directory: ["%kernel.cache_dir%"]
