AppBundle\Entity\NewsBoard:
    type: entity
    repositoryClass: AppBundle\Repository\NewsBoardRepository
    table: news_board

    id:
        id:
            type: string
            column: id
            generator:
                strategy: UUID

    fields:
        name:
            type: string
            length: 48

        description:
            type: string
            length: 256

        icon:
            type: string
            column: icon
            nullable: true


    oneToMany:
        feedSources:
            targetEntity: AppBundle\Entity\FeedSource
            mappedBy: newsBoard
